name: Test

on:
  push:
    branches: [next]
  pull_request:
    branches: [next]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: dtolnay/rust-toolchain@stable
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "latest"
      - run: npm install
      - run: npm run test
      - run: npm run build
