name: Test

on:
  push:
    branches: [next]
  pull_request:
    branches: [next]

jobs:
  build:
    runs_on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run test
      - run: npm run build
